name: Publish SDK on Release Merge

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  publish-pypi:
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'release/')
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Extract version from branch name
        id: extract_version
        run: |
          BRANCH="${{ github.event.pull_request.head.ref }}"
          VERSION="${BRANCH#release/v}"
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          pip install build twine
          pip install -r requirements.txt --quiet || true
          
      - name: Update version
        run: |
          if [ -f "setup.py" ]; then
            sed -i "s/version=['\"]*[0-9.]\+['\"]/version='${{ steps.extract_version.outputs.VERSION }}'/g" setup.py
          fi
          if [ -f "pyproject.toml" ]; then
            sed -i 's/version = "[0-9.]\+"/version = "${{ steps.extract_version.outputs.VERSION }}"/g' pyproject.toml
          fi
          
      - name: Build package
        run: python -m build
        
      - name: Publish to PyPI
        run: twine upload dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
          
      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.extract_version.outputs.VERSION }}
          release_name: Release v${{ steps.extract_version.outputs.VERSION }}
          body: |
            ## 🚀 SDK v${{ steps.extract_version.outputs.VERSION }} Released
            
            ### Installation
            ```bash
            pip install getbrand-sdk==${{ steps.extract_version.outputs.VERSION }}
            ```
            
            ### Changes
            See PR #${{ github.event.pull_request.number }} for details.
          draft: false
          prerelease: false